name = "backend"
compatibility_date = "2024-08-26"

# All environmental variable used in the Project is declared here 

[vars]

DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDlhODNjNjktOTVhYS00MzU5LWIwYzAtYjJiMzgyNDRhYzU5IiwidGVuYW50X2lkIjoiZjEyOTBlMDQzNzc1MDRiZjA3ZTU1YjUyZTc5YWU0M2M2NGVjNjVjNDJlMjAzMzU3ODk4YzYxZGJiNDFhODAzOCIsImludGVybmFsX3NlY3JldCI6ImM3ZjRhMWZmLTc4YzAtNGNjOC05MzQ4LTdiMzgwOGFjMTQ2NiJ9.rNvMX5gGAFpscKDumA5oe_a6sZZqAmYiSOf--3FYtBM"

JWT_SECRET = "Shishu"
